### ISSUE TITLE
Noticeable VC Offsets from Week 4 (High) to Week 5 (Winter-Horrorland)

### ISSUE THREAD

**Issue by Respnsbl6** [ImCodist/Friday-Night-Funkin-Gamemaker-Remake#17]
While trying to beat my FAVORITE week, Week 4, when I played the song High, the Voices went a bit faster.

That happened all the way to Eggnog, until Winter-Horroland stopped it.

This made no return after Eggnog or before High, but still is on running.

I'd really like this fixed, it's a little irritating...

**Comment by Yoshubs** [comment]
pretty sure this was already discovered I think it had something to do with gamemaker audio groups but don't quote me on that, I THINK it's fixed in the latest source but that won't be released until week 7 comes out officially (again, don't quote me on that, I'm not official help, just an occasional contributor)

**Comment by Respnsbl6** [comment]
...okay.

My current version was 0.0.0.2, I'll see if the newest download fixes it.
